dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - sudo apt-get -y install libfftw3-dev
install:
    # testing environment
    - pip install pycodestyle pytest pytest-cov sphinx sphinx_rtd_theme
    # requirements that are not part of setup.py
    - pip install tensorflow 
    - pip install git+https://github.com/FRBs/sigpyproc3
    - pip install .
script:
    - pytest -v
    - find . -name "*.py" -exec pycodestyle --ignore E501,E402,W503 {} +

jobs:
  include:
    - stage: deploy
      python: "3.8"
      install:
        - pip install sphinx sphinx_rtd_theme
        - pip install tensorflow
        - pip install git+https://github.com/FRBs/sigpyproc3
        - pip install .
      script:
        - make -C docs/ html
        - touch docs/_build/html/.nojekyll
      deploy:
        provider: pages:git
        verbose: true
        token: "$GITHUB_TOKEN"
        edge: true
        local_dir: "./docs/_build/html"
