dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - sudo apt-get -y install libfftw3-dev
install:
    # testing environment
    - pip install pycodestyle pytest pytest-cov sphinx
    # requirements that are not part of setup.py
    - pip install tensorflow git+https://github.com/FRBs/sigpyproc3
    - pip install .
script:
    - pytest
    - find . -name "*.py" -exec pycodestyle --ignore E501,E402,W503 {} +
