# DARC Master config
darc_master:
    log_file: "{home}/darc/log/darc_master.{hostname}.log"
    port: 51000  # NOTE: also hardcoded in darc_start_all_services
    socket_timeout: 30  # for creating socket
    stop_timeout: 5  # for stopping services
    services_master: ["voevent_generator", "status_website"]
    services_worker: ["amber_listener", "amber_triggering"]

# Status website
status_website:
    log_file: "{home}/darc/log/status_website.{hostname}.log"
    web_dir: "{home}/public_html/darc/status"
    check_services_master: ["voevent_generator"]
    check_services_worker: ["amber_listener", "amber_triggering"]
    interval: 30
    timeout: 10

# AMBER trigger listener
amber_listener:
    log_file: "{home}/darc/log/amber_listener.{hostname}.log"
    host: "localhost"
    port: 50000  # NOTE: also hardcoded as default in stream_files_to_port
    socket_timeout: 30
    poll_time: 0.1

# Direct processing of AMBER triggers
amber_triggering:
    log_file: "{home}/darc/log/amber_triggering.{hostname}.log"
    interval: 10
    #dm_min: 55
    #dm_max: 60
    dm_min: 0
    dm_max: 3000
    snr_min: 80
    age_max: 10

# VOEvent generator
voevent_generator:
    log_file: "{home}/darc/log/voevent_generator.{hostname}.log"
    voevent_dir: "{home}/darc/voevents"
    send_events: False
    broker_host: "arts041.apertif"
    broker_port: 8098

# Observation Control
observation_control:
    log_file: "{home}/darc/log/observation_control.{hostname}.log"
    timeout: 10
