# DARC Master config
darc_master:
    log_file: "{home}/darc/log/darc_master.{hostname}.log"
    port: 51000  # NOTE: also hardcoded in darc_start_all_services
    socket_timeout: 30  # for creating socket
    stop_timeout: 5  # for stopping services
    services_master: ["status_website"]
    services_worker: ["offline_processing"]
    commands: ['start_observation', 'stop_observation', 'abort_observation', 'status', 'start', 'stop', 'restart', 'stop_master']

# Status website
status_website:
    log_file: "{home}/darc/log/status_website.{hostname}.log"
    web_dir: "{home}/public_html/darc/status"
    interval: 10
    timeout: 10
    colour_good: "green"
    colour_bad: "red"
    colour_unknown: "grey"
    service_to_name:
        voevent_generator: "VOEvent generator"
        status_website: "Status website"
        amber_listener: "AMBER listener"
        amber_triggering: "AMBER triggering"
        offline_processing: "Offline processing"

# AMBER trigger listener
amber_listener:
    log_file: "{home}/darc/log/amber_listener.{hostname}.log"
    host: "localhost"
    port: 50000  # NOTE: also hardcoded as default in stream_files_to_port
    socket_timeout: 30
    poll_time: 0.1

# Direct processing of AMBER triggers
amber_triggering:
    log_file: "{home}/darc/log/amber_triggering.{hostname}.log"
    interval: 10
    #dm_min: 55
    #dm_max: 60
    dm_min: 0
    dm_max: 3000
    snr_min: 80
    age_max: 10

# Clustering of AMBER triggers
amber_clustering:
    log_file: "{home}/darc/log/amber_clustering.{hostname}.log"
    interval: 10
    dm_min: 0
    dm_max: 3000
    snr_min: 80
    age_max: 10

# VOEvent generator
voevent_generator:
    log_file: "{home}/darc/log/voevent_generator.{hostname}.log"
    voevent_dir: "{home}/darc/voevents"
    send_events: False
    broker_host: "arts041.apertif"
    broker_port: 8098

# Offline processing
offline_processing:
    log_file: "{home}/darc/log/offline_processing.{hostname}.log"
    interval: 10
    timeout: 10
    pthresh: 0.5
    cmap: 'viridis'
    ntime_plot: 64
    nfreq_plot: 128
    ndm: 1
    snrmin_processing: 10
    snrmin_processing_local: 5
    dmmin: 20
    dmmax: 5000
    ml_gpus: 0
    key_ntriggers_skipped: "ntriggers_skipped"
    keys_data: ["data_freq_time", "data_dm_time", "params", "tab"]
    model_dir: "{home}/keras_models"
    emailer: "{home}/ARTS-obs/emailer.py"
    triggering: "{home}/ARTS-obs/external/arts-analysis/triggers.py"
    classifier: "{home}/ARTS-obs/external/single_pulse_ml/single_pulse_ml/classify.py"
    trigger_to_master: "{home}/ARTS-obs/trigger_to_master.py"
    venv_dir: "{home}/python34"
