# DARC Master config
darc_master:
    log_file: "{home}/darc/log/darc_master.log"
    host: "localhost"
    port: 51000
    socket_timeout: 30  # for creating socket
    stop_timeout: 5  # for stopping services
    services: ["amber_listener", "amber_triggering", "voevent_generator", "status_website"]
    publish_status: True

# Status website
status_website:
    log_file: "{home}/darc/log/status_website.log"
    web_dir: "{home}/public_html/darc/status"

# AMBER trigger listener
amber_listener:
    log_file: "{home}/darc/log/amber_listener.log"
    host: "localhost"
    port: 50000  # NOTE: also hardcoded as default in stream_files_to_port
    socket_timeout: 30
    poll_time: 0.1

# Direct processing of AMBER triggers
amber_triggering:
    log_file: "{home}/darc/log/amber_triggering.log"
    interval: 10
    #dm_min: 55
    #dm_max: 60
    dm_min: 0
    dm_max: 3000
    snr_min: 80
    age_max: 10

# VOEvent generator
voevent_generator:
    log_file: "{home}/darc/log/voevent_generator.log"
    voevent_dir: "{home}/darc/voevents"
    send_events: False
    broker_host: "arts041.apertif"
    broker_port: 8098

